### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by beedawg1985** [h-a-graham/EAlidaR#28]
When I run:

`?EAlidaR::check_coverage()`

I get:

`Error in fetch(key) : lazy-load database '/home/barneyharris/R/x86_64-pc-linux-gnu-library/3.6/EAlidaR/help/EAlidaR.rdb' is corrupt `

**Comment by h-a-graham** [comment]
Thanks for this... Do any of these solutions work?
https://stackoverflow.com/questions/30424608/error-in-fetchkey-lazy-load-database

If not, I'll rebuild the documentation and see if that helps...

**Comment by h-a-graham** [comment]
Possible that this was caused by the inclusion of a % symbol... I've removed and rebuilt the docs for this. Hopefully fixed - will push this with the next PR hopefully also adressing the CRS issue.

**Comment by h-a-graham** [comment]
Hopefully fixed following recent update...
